// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbJMEW2sk1iZ-Z6GJ2P4gnfn0pvRp-BC0',
    appId: '1:154441437281:web:a1f1ade74db0e24c761a20',
    messagingSenderId: '154441437281',
    projectId: 'myvb-b853c',
    authDomain: 'myvb-b853c.firebaseapp.com',
    storageBucket: 'myvb-b853c.appspot.com',
    measurementId: 'G-ELSGB57VDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR8_bUtFJVc6TjkXNIdeG7uCFlG0w_JxU',
    appId: '1:154441437281:android:7015ce18514625da761a20',
    messagingSenderId: '154441437281',
    projectId: 'myvb-b853c',
    storageBucket: 'myvb-b853c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAULIbGxE0MfTLwEEUYwj90GfPJUIRetc',
    appId: '1:154441437281:ios:60cacb459754f8cb761a20',
    messagingSenderId: '154441437281',
    projectId: 'myvb-b853c',
    storageBucket: 'myvb-b853c.appspot.com',
    iosBundleId: 'com.fshangala.apps.myvb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAULIbGxE0MfTLwEEUYwj90GfPJUIRetc',
    appId: '1:154441437281:ios:311df8648f1ce32a761a20',
    messagingSenderId: '154441437281',
    projectId: 'myvb-b853c',
    storageBucket: 'myvb-b853c.appspot.com',
    iosBundleId: 'com.fshangala.apps.myvb.RunnerTests',
  );
}
