// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmtMwbb44zeaHzKwzXYiDhUsF9AkIB1ek',
    appId: '1:392028823949:web:37a9a6117622ebf4a4ddc4',
    messagingSenderId: '392028823949',
    projectId: 'myvb-cb1b4',
    authDomain: 'myvb-cb1b4.firebaseapp.com',
    storageBucket: 'myvb-cb1b4.appspot.com',
    measurementId: 'G-192JTZZYYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8JszxpRpLbhLU1wwF2bRZVFVziC03Irs',
    appId: '1:392028823949:android:cfa3c37e6ce17c82a4ddc4',
    messagingSenderId: '392028823949',
    projectId: 'myvb-cb1b4',
    storageBucket: 'myvb-cb1b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBayGyB4bRYS7AFKBRFYAZCMOp0mS7RdLY',
    appId: '1:392028823949:ios:b742c947612b1eeea4ddc4',
    messagingSenderId: '392028823949',
    projectId: 'myvb-cb1b4',
    storageBucket: 'myvb-cb1b4.appspot.com',
    iosBundleId: 'com.fshangala.apps.myvb',
  );
}
